-- 1. Obtener los nombres de todos los alumnos junto con el nombre de la promoción a la que pertenecen.
SELECT
	A.NOMBRE_COMPLETO, CONCAT(P.NOMBRE,' ', EXTRACT(YEAR FROM P.FECHA_COMIENZO)) AS PROMOCION
FROM
	ALUMNOS AS A
INNER JOIN
	ALUM_PROM AS AP ON A.ID_ALUMNO = AP.ID_ALUMNO
INNER JOIN
	PROMOCIONES AS P ON AP.ID_PROMOCION = P.ID_PROMOCION;
-- 2. LISTAR LOS PROYECTOS QUE HAN SIDO REALIZADOS POR ALUMNOS DE LA PROMOCIÓN DE SEPTIEMBRE 2023.
SELECT
	A.NOMBRE_COMPLETO, CONCAT(P.NOMBRE,' ', EXTRACT(YEAR FROM P.FECHA_COMIENZO)) AS PROMOCION,
	PR.NOMBRE AS PROYECTO
FROM
	ALUMNOS AS A
INNER JOIN
	ALUM_PROM AS AP ON A.ID_ALUMNO = AP.ID_ALUMNO
INNER JOIN
	PROMOCIONES AS P ON AP.ID_PROMOCION = P.ID_PROMOCION
INNER JOIN
	RESULTADO_PROYECTOS AS RP ON A.ID_ALUMNO = RP.ID_ALUMNO
INNER JOIN
	PROYECTOS AS PR ON RP.ID_PROYECTO = PR.ID_PROYECTO
WHERE
	EXTRACT(YEAR FROM P.FECHA_COMIENZO) = 2023
LIMIT 5;
-- 3. ENCONTRAR EL NÚMERO TOTAL DE ALUMNOS EN CADA PROMOCIÓN.
SELECT
    CONCAT(P.NOMBRE, ' ', EXTRACT(YEAR FROM P.FECHA_COMIENZO)) AS PROMOCION,
    COUNT(A.ID_ALUMNO)
FROM
    ALUMNOS AS A
INNER JOIN
    ALUM_PROM AS AP ON A.ID_ALUMNO = AP.ID_ALUMNO
INNER JOIN
    PROMOCIONES AS P ON AP.ID_PROMOCION = P.ID_PROMOCION
GROUP BY PROMOCION;
-- 4. OBTENER LOS NOMBRES DE LOS INSTRUCTORES (TA) QUE ESTÁN ASOCIADOS A PROMOCIONES DEL CAMPUS DE MADRID.
SELECT
	C.NOMBRE_COMPLETOCONCAT(P.NOMBRE, ' ', EXTRACT(YEAR FROM P.FECHA_COMIENZO)) AS PROMOCION
FROM
	CLAUSTRO AS C
INNER JOIN PROMOCION_ASOCIADA AS PR ON C.ID_CLAUSTRO = PR.ID_CLAUSTRO
INNER JOIN PROMOCIONES AS P ON PR.ID_PROMOCION = P.ID_PROMOCION
INNER JOIN CAMPUS ON PR.ID_CAMPUS = CAMPUS.ID_CAMPUS
WHERE C.ROL LIKE '%TA%'