DROP TABLE IF EXISTS campus,proyectos,promociones,verticales,alumnos,claustro,resultado_proyectos,promocion_asociada, CASCADE;

-- Crear tabla campus .
CREATE TABLE campus(
  id_campus serial NOT NULL PRIMARY KEY, 
  nombre varchar(45) NOT NULL
);

-- Crear tabla promociones .
CREATE TABLE promociones(
  id_promocion serial NOT NULL PRIMARY KEY, 
  nombre varchar(45) NOT NULL, 
  fecha_comienzo date NOT NULL
);

-- Crear tabla verticales .
CREATE TABLE verticales(
  id_vertical serial NOT NULL PRIMARY KEY, 
  nombre varchar(45) NOT NULL
);
-- Crear tabla proyectos .
CREATE TABLE proyectos(
  id_proyecto serial NOT NULL PRIMARY KEY, 
  nombre varchar(45) NOT NULL,
  id_vertical int NOT NULL,
  FOREIGN KEY (id_vertical) REFERENCES verticales(id_vertical)
);

-- Crear tabla alumnos .
CREATE TABLE alumnos(
  id_alumno serial NOT NULL PRIMARY KEY, 
  nombre_completo varchar(45) NOT NULL, 
  email varchar(100) NOT NULL UNIQUE,
  modalidad varchar(100) NOT NULL
);

-- Crear tabla alumnos
CREATE TABLE alum_prom (
  id_alumno int NOT NULL , 
  id_promocion int NOT NULL,
  FOREIGN KEY (id_alumno) REFERENCES alumnos(id_alumno),
  FOREIGN KEY (id_promocion) REFERENCES promociones(id_promocion)
);

-- Crear tabla claustro .
CREATE TABLE claustro(
  id_claustro serial NOT NULL PRIMARY KEY, 
  nombre_completo varchar(45) NOT NULL, 
  email varchar(100) NOT NULL UNIQUE,
  id_vertical int NOT NULL,
  modalidad varchar(100) NOT NULL,
  rol varchar(100) NOT NULL,
  FOREIGN KEY (id_vertical) REFERENCES verticales(id_vertical)
);


-- Crear tabla resultado proyectos (tabla intermedia) .
CREATE TABLE resultado_proyectos(
  id_proyecto int NOT NULL, 
  id_alumno int NOT NULL,
  calificacion varchar(45),
  FOREIGN KEY (id_proyecto) REFERENCES proyectos(id_proyecto),
  FOREIGN KEY (id_alumno) REFERENCES alumnos(id_alumno)
);

-- Crear tabla promocion_asociada (tabla intermedia) .
CREATE TABLE promocion_asociada(
  id_claustro int NOT NULL,
  id_promocion int NOT NULL,
  id_campus int NOT NULL,
  FOREIGN KEY (id_claustro) REFERENCES claustro(id_claustro),
  FOREIGN KEY (id_promocion) REFERENCES promociones(id_promocion),
  FOREIGN KEY (id_campus) REFERENCES campus(id_campus)
);

INSERT INTO campus(nombre)
VALUES
	('Madrid'),
	('Barcelona'),
	('Valencia');

INSERT INTO verticales(nombre)
VALUES
	('DS'),
	('FS');

INSERT INTO proyectos(nombre, id_vertical)
VALUES
	('Proyecto_HLF', 1), 
	('Proyecto_EDA', 1), 
	('Proyecto_BBDD', 1), 
	('Proyecto_ML', 1), 
	('Proyecto_Deployment', 1), 
	('Proyecto_WebDev', 2), 
	('Proyecto_FrontEnd', 2), 
	('Proyecto_Backend', 2), 
	('Proyecto_React', 2), 
	('Proyecto_FullStack', 2);

INSERT INTO promociones(nombre, fecha_comienzo)
VALUES
	('Septiembre', '2023-09-18'), 
	('Febrero', '2024-02-12'); 

INSERT INTO claustro(nombre_completo, email, id_vertical, modalidad,rol)
VALUES
	('Noa Yáñez', 'noayanez@dominio.com', 1, 'Presencial', 'TA'),
 	('Saturnina Benitez', 'saturtinabenitez@dominio.com', 1, 'Presencial', 'TA'),
 	('Anna Feliu', 'annafeliu@dominio.com', 2, 'Presencial', 'TA'),
 	('Rosalva Ayuso', 'rosalvaayuso@dominio.com', 2, 'Presencial', 'TA'),
 	('Ana Sofía Ferrer', 'anasofiaferrer@dominio.com', 2, 'Presencial', 'TA'),
 	('Angélica Corral', 'angelicacorral@dominio.com', 2, 'Presencial', 'TA'),
 	('Ariel Lledó', 'ariellledo@dominio.com', 1, 'Presencial', 'TA'),
 	('Mario Prats', 'marioprats@dominio.com', 2, 'Online', 'LI'),
 	('Luis Ángel Suárez', 'luisangelsuarez@dominio.com', 2, 'Online', 'LI'),
 	('María Dolores Diaz', 'mariadoloresdiaz@dominio.com', 1, 'Online', 'LI');

INSERT INTO alumnos(nombre_completo, email, modalidad)
VALUES
	('Jafet Casals', 'jafet_casals@gmail.com', 'Presencial'),
	('Jorge Manzanares', 'jorge_manzanares@gmail.com', 'Presencial'),
	('Onofre Adadia', 'onofre_adadia@gmail.com', 'Presencial'),
	('Merche Prada', 'merche_prada@gmail.com', 'Online'),
	('Pilar Abella', 'pilar_abella@gmail.com', 'Online'),
	('Leoncio Tena', 'leoncio_tena@gmail.com', 'Presencial'),
	('Odalys Torrijos', 'odalys_torrijos@gmail.com', 'Online'),
	('Eduardo Caparrós', 'eduardo_caparros@gmail.com', 'Presencial'),
	('Ignacio Goicoechea', 'ignacio_goicoechea@gmail.com', 'Online'),
	('Clementina Santos', 'clementina_santos@gmail.com', 'Presencial'),
	('Daniela Falcó', 'daniela_falco@gmail.com', 'Online'),
	('Abraham Vélez', 'abraham_velez@gmail.com', 'Presencial'),
	('Maximiliano Menéndez', 'maximiliano_menendez@gmail.com', 'Online'),
	('Anita Heredia', 'anita_heredia@gmail.com', 'Presencial'),
	('Eli Casas', 'eli_casas@gmail.com', 'Presencial'),
	('Guillermo Borrego', 'guillermo_borrego@gmail.com', 'Online'),
	('Sergio Aguirre', 'sergio_aguirre@gmail.com', 'Presencial'),
	('Carlito Carrión', 'carlito_carrion@gmail.com', 'Presencial'),
	('Haydée Figueroa', 'haydee_figueroa@gmail.com', 'Online'),
	('Chita Mancebo', 'chita_mancebo@gmail.com', 'Presencial'),
	('Joaquina Asensio', 'joaquina_asensio@gmail.com', 'Presencial'),
	('Cristian Sarabia', 'cristian_sarabia@gmail.com', 'Online'),
	('Isabel Ibáñez', 'isabel_ibañez@gmail.com', 'Presencial'),
	('Desiderio Jordá', 'desiderio_jorda@gmail.com', 'Online'),
	('Rosalina Llanos', 'rosalina_llanos@gmail.com', 'Online'),
	('Amor Larrañaga', 'amor_larrañaga@gmail.com', 'Online'),
	('Teodoro Alberola', 'teodoro_alberola@gmail.com', 'Presencial'),
	('Cleto Plana', 'cleto_plana@gmail.com', 'Presencial'),
	('Aitana Sebastián', 'aitana_sebastian@gmail.com', 'Presencial'),
	('Dolores Valbuena', 'dolores_valbuena@gmail.com', 'Presencial'),
	('Julie Ferrer', 'julie_ferrer@gmail.com', 'Online'),
	('Mireia Cabañas', 'mireia_cabañas@gmail.com', 'Online'),
	('Flavia Amador', 'flavia_amador@gmail.com', 'Presencial'),
	('Albino Macias', 'albino_macias@gmail.com', 'Online'),
	('Ester Sánchez', 'ester_sanchez@gmail.com', 'Presencial'),
	('Luis Miguel Galvez', 'luis_miguel_galvez@gmail.com', 'Presencial'),
	('Loida Arellano', 'loida_arellano@gmail.com', 'Presencial'),
	('Heraclio Duque', 'heraclio_duque@gmail.com', 'Presencial'),
	('Herberto Figueras', 'herberto_figueras@gmail.com', 'Presencial'),
	('Teresa Laguna', 'teresa_laguna@gmail.com', 'Presencial'),
	('Estrella Murillo', 'estrella_murillo@gmail.com', 'Online'),
	('Ernesto Uriarte', 'ernesto_uriarte@gmail.com', 'Online'),
	('Daniela Guitart', 'daniela_guitart@gmail.com', 'Online'),
	('Timoteo Trillo', 'timoteo_trillo@gmail.com', 'Presencial'),
	('Ricarda Tovar', 'ricarda_tovar@gmail.com', 'Presencial'),
	('Alejandra Vilaplana', 'alejandra_vilaplana@gmail.com','Presencial'),
	('Daniel Rosselló', 'daniel_rossello@gmail.com', 'Presencial'),
	('Rita Olivares', 'rita_olivares@gmail.com', 'Presencial'),
	('Cleto Montes', 'cleto_montes@gmail.com', 'Online'),
	('Marino Castilla', 'marino_castilla@gmail.com', 'Online'),
	('Estefanía Valcárcel', 'estefania_valcarcel@gmail.com', 'Online'),
	('Noemí Vilanova', 'noemi_vilanova@gmail.com', 'Online');

INSERT INTO alum_prom(id_alumno, id_promocion)
VALUES
	(1, 1),
	(2, 1),
	(3, 1),
	(4, 1),
	(5, 1),
	(6, 1),
	(7, 1),
	(8, 1),
	(9, 1),
	(10, 1),
	(11, 1),
	(12, 1),
	(13, 1),
	(14, 1),
	(15, 1),
	(16, 2),
	(17, 2),
	(18, 2),
	(19, 2),
	(20, 2),
	(21, 2),
	(22, 2),
	(23, 2),
	(24, 2),
	(25, 2),
	(26, 1),
	(27, 1),
	(28, 1),
	(29, 1),
	(30, 1),
	(31, 1),
	(32, 1),
	(33, 1),
	(34, 1),
	(35, 1),
	(36, 1),
	(37, 1),
	(38, 1),
	(39, 1),
	(40, 2),
	(41, 2),
	(42, 2),
	(43, 2),
	(44, 2),
	(45, 2),
	(46, 2),
	(47, 2),
	(48, 2),
	(49, 2),
	(50, 2),
	(51, 2),
	(52, 2);

INSERT INTO promocion_asociada(id_claustro, id_promocion,id_campus)
VALUES
	(1,1,1),
	(2,1,1),
	(3,1,1),
	(4,1,2),
	(5,2,2),
	(6,2,1),
	(7,1,1),
	(8,2,2),
	(9,1,1),
	(10,1,1);

INSERT INTO resultado_proyectos(id_alumno, id_proyecto, calificacion)
VALUES
	(1, 1, 'Apto'),
	(2, 1, 'Apto'),
	(3, 1, 'Apto'),
	(4, 1, 'Apto'),
	(5, 1, 'Apto'),
	(6, 1, 'Apto'),
	(7, 1, 'No Apto'),
	(8, 1, 'No Apto'),
	(9, 1, 'Apto'),
	(10, 1, 'Apto'),
	(11, 1, 'Apto'),
	(12, 1, 'Apto'),
	(13, 1, 'Apto'),
	(14, 1, 'Apto'),
	(15, 1, 'Apto'),
	(16, 1, 'Apto'),
	(17, 1, 'Apto'),
	(18, 1, 'Apto'),
	(19, 1, 'Apto'),
	(20, 1, 'No Apto'),
	(21, 1, 'No Apto'),
	(22, 1, 'Apto'),
	(23, 1, 'No Apto'),
	(24, 1, 'No Apto'),
	(25, 1, 'Apto'),
	(1, 2, 'No Apto'),
	(2, 2, 'No Apto'),
	(3, 2, 'Apto'),
	(4, 2, 'No Apto'),
	(5, 2, 'No Apto'),
	(6, 2, 'Apto'),
	(7, 2, 'Apto'),
	(8, 2, 'Apto'),
	(9, 2, 'Apto'),
	(10, 2, 'No Apto'),
	(11, 2, 'Apto'),
	(12, 2, 'No Apto'),
	(13, 2, 'No Apto'),
	(14, 2, 'Apto'),
	(15, 2, 'Apto'),
	(16, 2, 'No Apto'),
	(17, 2, 'No Apto'),
	(18, 2, 'No Apto'),
	(19, 2, 'Apto'),
	(20, 2, 'Apto'),
	(21, 2, 'No Apto'),
	(22, 2, 'Apto'),
	(23, 2, 'Apto'),
	(24, 2, 'Apto'),
	(25, 2, 'Apto'),
	(1, 3, 'Apto'),
	(2, 3, 'Apto'),
	(3, 3, 'Apto'),
	(4, 3, 'No Apto'),
	(5, 3, 'Apto'),
	(6, 3, 'Apto'),
	(7, 3, 'Apto'),
	(8, 3, 'Apto'),
	(9, 3, 'Apto'),
	(10, 3, 'Apto'),
	(11, 3, 'Apto'),
	(12, 3, 'No Apto'),
	(13, 3, 'Apto'),
	(14, 3, 'Apto'),
	(15, 3, 'Apto'),
	(16, 3, 'No Apto'),
	(17, 3, 'Apto'),
	(18, 3, 'Apto'),
	(19, 3, 'Apto'),
	(20, 3, 'No Apto'),
	(21, 3, 'Apto'),
	(22, 3, 'No Apto'),
	(23, 3, 'No Apto'),
	(24, 3, 'No Apto'),
	(25, 3, 'Apto'),
	(1, 4, 'Apto'),
	(2, 4, 'Apto'),
	(3, 4, 'No Apto'),
	(4, 4, 'Apto'),
	(5, 4, 'Apto'),
	(6, 4, 'Apto'),
	(7, 4, 'Apto'),
	(8, 4, 'Apto'),
	(9, 4, 'No Apto'),
	(10, 4, 'Apto'),
	(11, 4, 'Apto'),
	(12, 4, 'Apto'),
	(13, 4, 'Apto'),
	(14, 4, 'Apto'),
	(15, 4, 'Apto'),
	(16, 4, 'Apto'),
	(17, 4, 'Apto'),
	(18, 4, 'Apto'),
	(19, 4, 'Apto'),
	(20, 4, 'Apto'),
	(21, 4, 'Apto'),
	(22, 4, 'Apto'),
	(23, 4, 'Apto'),
	(24, 4, 'No Apto'),
	(25, 4, 'Apto'),
	(1, 5, 'Apto'),
	(2, 5, 'Apto'),
	(3, 5, 'Apto'),
	(4, 5, 'No Apto'),
	(5, 5, 'Apto'),
	(6, 5, 'Apto'),
	(7, 5, 'Apto'),
	(8, 5, 'Apto'),
	(9, 5, 'Apto'),
	(10, 5, 'Apto'),
	(11, 5, 'Apto'),
	(12, 5, 'Apto'),
	(13, 5, 'Apto'),
	(14, 5, 'Apto'),
	(15, 5, 'Apto'),
	(16, 5, 'No Apto'),
	(17, 5, 'No Apto'),
	(18, 5, 'Apto'),
	(19, 5, 'Apto'),
	(20, 5, 'Apto'),
	(21, 5, 'Apto'),
	(22, 5, 'Apto'),
	(23, 5, 'Apto'),
	(24, 5, 'Apto'),
	(25, 5, 'Apto'),
	(26, 6, 'Apto'),
	(27, 6, 'No Apto'),
	(28, 6, 'Apto'),
	(29, 6, 'Apto'),
	(30, 6, 'Apto'),
	(31, 6, 'No Apto'),
	(32, 6, 'No Apto'),
	(33, 6, 'Apto'),
	(34, 6, 'No Apto'),
	(35, 6, 'No Apto'),
	(36, 6, 'No Apto'),
	(37, 6, 'Apto'),
	(38, 6, 'Apto'),
	(39, 6, 'Apto'),
	(40, 6, 'Apto'),
	(41, 6, 'Apto'),
	(42, 6, 'Apto'),
	(43, 6, 'Apto'),
	(44, 6, 'No Apto'),
	(45, 6, 'Apto'),
	(46, 6, 'No Apto'),
	(47, 6, 'No Apto'),
	(48, 6, 'No Apto'),
	(49, 6, 'Apto'),
	(50, 6, 'No Apto'),
	(51, 6, 'Apto'),
	(52, 6, 'Apto'),
	(26, 7, 'Apto'),
	(27, 7, 'No Apto'),
	(28, 7, 'No Apto'),
	(29, 7, 'No Apto'),
	(30, 7, 'Apto'),
	(31, 7, 'No Apto'),
	(32, 7, 'Apto'),
	(33, 7, 'Apto'),
	(34, 7, 'Apto'),
	(35, 7, 'Apto'),
	(36, 7, 'Apto'),
	(37, 7, 'Apto'),
	(38, 7, 'Apto'),
	(39, 7, 'Apto'),
	(40, 7, 'Apto'),
	(41, 7, 'Apto'),
	(42, 7, 'Apto'),
	(43, 7, 'No Apto'),
	(44, 7, 'Apto'),
	(45, 7, 'Apto'),
	(46, 7, 'No Apto'),
	(47, 7, 'No Apto'),
	(48, 7, 'No Apto'),
	(49, 7, 'Apto'),
	(50, 7, 'No Apto'),
	(51, 7, 'Apto'),
	(52, 7, 'No Apto'),
	(26, 8, 'Apto'),
	(27, 8, 'Apto'),
	(28, 8, 'Apto'),
	(29, 8, 'Apto'),
	(30, 8, 'Apto'),
	(31, 8, 'No Apto'),
	(32, 8, 'Apto'),
	(33, 8, 'No Apto'),
	(34, 8, 'Apto'),
	(35, 8, 'Apto'),
	(36, 8, 'Apto'),
	(37, 8, 'Apto'),
	(38, 8, 'No Apto'),
	(39, 8, 'Apto'),
	(40, 8, 'Apto'),
	(41, 8, 'No Apto'),
	(42, 8, 'Apto'),
	(43, 8, 'No Apto'),
	(44, 8, 'Apto'),
	(45, 8, 'Apto'),
	(46, 8, 'No Apto'),
	(47, 8, 'Apto'),
	(48, 8, 'No Apto'),
	(49, 8, 'No Apto'),
	(50, 8, 'Apto'),
	(51, 8, 'No Apto'),
	(52, 8, 'No Apto'),
	(26, 9, 'Apto'),
	(27, 9, 'No Apto'),
	(28, 9, 'No Apto'),
	(29, 9, 'No Apto'),
	(30, 9, 'Apto'),
	(31, 9, 'Apto'),
	(32, 9, 'Apto'),
	(33, 9, 'Apto'),
	(34, 9, 'Apto'),
	(35, 9, 'No Apto'),
	(36, 9, 'Apto'),
	(37, 9, 'Apto'),
	(38, 9, 'No Apto'),
	(39, 9, 'Apto'),
	(40, 9, 'Apto'),
	(41, 9, 'Apto'),
	(42, 9, 'Apto'),
	(43, 9, 'Apto'),
	(44, 9, 'Apto'),
	(45, 9, 'Apto'),
	(46, 9, 'Apto'),
	(47, 9, 'No Apto'),
	(48, 9, 'Apto'),
	(49, 9, 'Apto'),
	(50, 9, 'No Apto'),
	(51, 9, 'No Apto'),
	(52, 9, 'Apto'),
	(26, 10, 'No Apto'),
	(27, 10, 'Apto'),
	(28, 10, 'Apto'),
	(29, 10, 'Apto'),
	(30, 10, 'No Apto'),
	(31, 10, 'No Apto'),
	(32, 10, 'Apto'),
	(33, 10, 'Apto'),
	(34, 10, 'Apto'),
	(35, 10, 'Apto'),
	(36, 10, 'Apto'),
	(37, 10, 'Apto'),
	(38, 10, 'No Apto'),
	(39, 10, 'Apto'),
	(40, 10, 'Apto'),
	(41, 10, 'Apto'),
	(42, 10, 'Apto'),
	(43, 10, 'Apto'),
	(44, 10, 'No Apto'),
	(45, 10, 'Apto'),
	(46, 10, 'Apto'),
	(47, 10, 'No Apto'),
	(48, 10, 'Apto'),
	(49, 10, 'Apto'),
	(50, 10, 'No Apto'),
	(51, 10, 'Apto'),
	(52, 10, 'Apto');
